version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: Share-It-Gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    container_name: Share-It-Server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_NAME=shareit
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=postgresshareit
      - POSTGRES_PASSWORD=postgresshareit

  db:
    image: postgres:14.0-alpine
    container_name: Share-It-DB
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgresshareit
      - POSTGRES_PASSWORD=postgresshareit