DROP TABLE IF EXISTS users, items, requests, bookings, comments CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    user_id    INT AUTO_INCREMENT PRIMARY KEY,
    user_name  VARCHAR(255) NOT NULL,
    user_email VARCHAR(255) NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS items
(
    item_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name        VARCHAR(255)                                     NOT NULL,
    item_description VARCHAR(2000)                                    NOT NULL,
    item_available   BOOLEAN DEFAULT true                             NOT NULL,
    owner_id         INT REFERENCES users (user_id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP                                        NOT NULL,
    end_date   TIMESTAMP                                        NOT NULL,
    item_id    INT REFERENCES items (item_id) ON DELETE CASCADE NOT NULL,
    booker_id  INT REFERENCES users (user_id) ON DELETE CASCADE NOT NULL,
    status     VARCHAR                                          NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_text VARCHAR(2000)                                    NOT NULL,
    item_id      INT REFERENCES items (item_id) ON DELETE CASCADE NOT NULL,
    user_id      INT REFERENCES users (user_id) ON DELETE CASCADE NOT NULL,
    created      TIMESTAMP                                        NOT NULL
);