DROP TABLE IF EXISTS users, items, requests, bookings, comments CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    user_id    INT AUTO_INCREMENT PRIMARY KEY,
    user_name  VARCHAR(255) NOT NULL,
    user_email VARCHAR      NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS items
(
    item_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name        VARCHAR(255) NOT NULL,
    item_description VARCHAR(2000),
    item_available   BOOLEAN DEFAULT 'true',
    owner_id          INT REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP,
    end_date   TIMESTAMP,
    item_id    INT REFERENCES items (item_id) ON DELETE CASCADE,
    booker_id    INT REFERENCES users (user_id) ON DELETE CASCADE,
    status     VARCHAR
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       VARCHAR(2000),
    item_id    INT REFERENCES items (item_id) ON DELETE CASCADE,
    user_id    INT REFERENCES users (user_id) ON DELETE CASCADE,
    created     TIMESTAMP WITHOUT TIME ZONE
);