DROP TABLE IF EXISTS users, items, requests, bookings, comments CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    user_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name  VARCHAR(255) NOT NULL,
    user_email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS item_requests
(
    item_request_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description     VARCHAR(2000) NOT NULL,
    user_id         BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    created         TIMESTAMP     NOT NULL
);


CREATE TABLE IF NOT EXISTS items
(
    item_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name        VARCHAR(255)           NOT NULL,
    item_description VARCHAR(2000)          NOT NULL,
    item_available   BOOLEAN DEFAULT 'true' NOT NULL,
    owner_id         INT REFERENCES users (user_id) ON DELETE CASCADE,
    item_request_id  BIGINT REFERENCES item_requests (item_request_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP NOT NULL,
    end_date   TIMESTAMP NOT NULL,
    item_id    INT REFERENCES items (item_id) ON DELETE CASCADE,
    booker_id  INT REFERENCES users (user_id) ON DELETE CASCADE,
    status     VARCHAR   NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_text VARCHAR(2000) NOT NULL,
    item_id      INT REFERENCES items (item_id) ON DELETE CASCADE,
    user_id      INT REFERENCES users (user_id) ON DELETE CASCADE,
    created      TIMESTAMP     NOT NULL
);


CREATE TABLE IF NOT EXISTS items_requests
(
    item_id         INT REFERENCES items (item_id) ON DELETE CASCADE,
    item_request_id INT REFERENCES item_requests (item_request_id) ON DELETE CASCADE,
    PRIMARY KEY (item_id, item_request_id)
);